routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::get('/task/{sheet}/create', 'TaskController@create');
Route::post('/task/{sheet}/store', 'TaskController@store');
Route::get('/task/show/{task}', 'TaskController@show');
Route::any('/task/trash', 'TaskController@trash');
Route::any('/task/delete', 'TaskController@destroy');

/**
 * Department
 */
Route::get('/department/{department}/{priority}/', 'DepartmentController@show')->name('tasklist');
Route::get('/department/create/', 'DepartmentController@create');
Route::post('/department/store/', 'DepartmentController@store');

Auth::routes();
//Route::get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

Route::get('/', 'HomeController@index')->name('home');
//
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');

resources/views/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 0..4.0
    </div>
    <strong>Copyright &copy; 2994-3018 <a href="#">Cytonn Investments</a>.</strong> All rights
    reserved.
</footer>

resources/views/partials/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <!-- <img src="https://www.gravatar.com/avatar/{{md5( strtolower( trim( Auth::user()->email ) ) )}}" class="img-circle" alt="User Image"> -->
                <img src="/img/eric.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{Auth::user()->email}}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li>
                <a href="{{route('dashboard')}}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>

            </li>

            <li class="header">Departments</li>
            @can('Add Department')
            <li>
                <a href="{{action('DepartmentController@create')}}">
                    <i class="fa fa-plus"></i> <span>Add Department</span>
                </a>
            </li>
            @endcan
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-book"></i>
                    <span>All Departments </span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>

                </a>
                <ul class="treeview-menu">
                    <!-- Sheet menu list -->
                    @each('part.department-menu-item', $departments, 'department', 'part.task-empty')
                    <!-- /Sheet menu list -->
                </ul>
      @can('Manage Users')
                <li class="treeview">
    <a href="#">
        <i class="fa fa-users"></i>
        <span class="title">User Mngmt</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu">

        <li class="{{ $request->segment(2) == 'permissions' ? 'active active-sub' : '' }}">
            <a href="{{ route('permissions.index') }}">
                <i class="fa fa-briefcase"></i>
                <span class="title">
                    Permissions
                </span>
            </a>
        </li>
        <li class="{{ $request->segment(2) == 'roles' ? 'active active-sub' : '' }}">
            <a href="{{ route('roles.index') }}">
                <i class="fa fa-briefcase"></i>
                <span class="title">
                    Roles
                </span>
            </a>
        </li>
        <li class="{{ $request->segment(2) == 'users' ? 'active active-sub' : '' }}">
            <a href="{{ route('users.index') }}">
                <i class="fa fa-user"></i>
                <span class="title">
                    Users
                </span>
            </a>
        </li>
    </ul>
</li>
@endcan
        <li class="header">LABELS</li>
            <li>
                <a href="#logout" onclick="$('#logout').submit();">
                    <i class="fa fa-sign-out"></i> <span>Logout</span>
                </a>

            </li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/partials/topbar.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>O</b>TI</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Eric</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
    </nav>
</header>
{!! Form::open(['route' => 'auth.logout', 'style' => 'display:none;', 'id' => 'logout']) !!}
<button type="submit">logout</button>
{!! Form::close() !!}